In [59]:
# import dependencies
import numpy
import matplotlib.pyplot as plt
import pandas as pd

In [86]:
# 
samples = ["med_p1-5", "med_p2-5", "high_p1-4", "high_"]
# variable x is the wavelength of the spectrophotometer 
x_values = [200.0, 205.0, 210.0, 215.0, 220.0, 225.0, 230.0, 235.0, 240.0, 245.0,
     250.0, 255.0, 260.0, 265.0, 270.0, 275.0, 280.0, 285.0, 290.0, 295.0,
     300.0, 305.0, 310.0, 315.0, 320.0, 325.0, 330.0, 335.0, 340.0, 345.0,
     350.0, 355.0, 360.0, 365.0, 370.0, 375.0, 380.0, 385.0, 390.0, 395.0, 400] 
# wavelength DataFrame
x = pd.DataFrame(x_values)
# l_df

med_p1_5 = [0.142,0.114, 0.092, 0.067, 0.150, 0.348, 1.216, 1.374, 1.043, 0.650,
              0.372, 0.206, 0.128, 0.100, 0.088, 0.080, 0.072, 0.064, 0.054, 0.045,
              0.039, 0.033, 0.029, 0.025, 0.022, 0.019, 0.017, 0.015, 0.013, 0.011,
              0.010, 0.009, 0.008, 0.007, 0.006, 0.006, 0.005, 0.005, 0.004, 0.004,
              0.003]

In [87]:
# x values are the wavelength range from 200 nm to 400 nm of the spectra analysis
x = l_df.rename(columns={x.columns[0]: "wavelength"})
# x

In [88]:
# y1 values are the OD, absorbance reading of the fraction with the heighest protein concentration and highest OD after ammonium percepitation. 

y1 = pd.DataFrame(od_med_p1_5)
# y1 corresponds to med_p1_5

In [98]:
y1 = y1.rename(columns={y1.columns[0]: "Absorbance P1-5 Med"})

In [99]:
# combining x and y axis; from the two DataFrames
spectra_med_p1_5 = pd.concat([x,y1], axis=1)

In [101]:
df1 = spectra_med_p1_5.rename(columns={spectra_med_p1_5.columns[0]: "Wavelength"})
df1

    Wavelength  Absorbance P1-5 Med
0        200.0                0.142
1        205.0                0.114
2        210.0                0.092
3        215.0                0.067
4        220.0                0.150
5        225.0                0.348
6        230.0                1.216
7        235.0                1.374
8        240.0                1.043
9        245.0                0.650
10       250.0                0.372
11       255.0                0.206
12       260.0                0.128
13       265.0                0.100
14       270.0                0.088
15       275.0                0.080
16       280.0                0.072
17       285.0                0.064
18       290.0                0.054
19       295.0                0.045
20       300.0                0.039
21       305.0                0.033
22       310.0                0.029
23       315.0                0.025
24       320.0                0.022
25       325.0                0.019
26       330.0                0.017
27       335.0                0.015
28       340.0                0.013
29       345.0                0.011
30       350.0                0.010
31       355.0                0.009
32       360.0                0.008
33       365.0                0.007
34       370.0                0.006
35       375.0                0.006
36       380.0                0.005
37       385.0                0.005
38       390.0                0.004
39       395.0                0.004
40       400.0                0.003

In [102]:
# df.to_excel (r'C:\Users\chris\mcb-protein_isolation\data\dataspectra_med_p1_5.xlsx', index = False, header=True)

In [103]:
# P2-5 MED Salt
# Highest absorbance read at 280 nm ~ 0.007 
y2 = [0.251,0.257,0.432,0.373,0.384,0.720,1.486,2.020,2.451,1.990,
     1.405,1.097,1.032,1.079,1.156,1.199,1.154,0.994,0.758,0.497,
     0.360,0.285,0.254,0.237,0.225,0.213,0.197,0.182,0.167,0.155,
     0.145,0.138,0.132,0.127,0.121,0.116,0.111,0.105,0.099,0.094,0.089]

y2_df = pd.DataFrame(y2)

In [104]:
y2_df = y2_df.rename(columns = {y2_df.columns[0]: "Absorbance P2-5 Med"})

In [105]:
y2_df

    Absorbance P2-5 Med
0                 0.251
1                 0.257
2                 0.432
3                 0.373
4                 0.384
5                 0.720
6                 1.486
7                 2.020
8                 2.451
9                 1.990
10                1.405
11                1.097
12                1.032
13                1.079
14                1.156
15                1.199
16                1.154
17                0.994
18                0.758
19                0.497
20                0.360
21                0.285
22                0.254
23                0.237
24                0.225
25                0.213
26                0.197
27                0.182
28                0.167
29                0.155
30                0.145
31                0.138
32                0.132
33                0.127
34                0.121
35                0.116
36                0.111
37                0.105
38                0.099
39                0.094
40                0.089

In [108]:
# df = spectra_p1_5_med

In [106]:
spectra_p1_5_med = pd.concat([x, y1, y2_df], axis=1)
spectra_p1_5_med

    Wavelength  Absorbance P1-5 Med  Absorbance P2-5 Med
0        200.0                0.142                0.251
1        205.0                0.114                0.257
2        210.0                0.092                0.432
3        215.0                0.067                0.373
4        220.0                0.150                0.384
5        225.0                0.348                0.720
6        230.0                1.216                1.486
7        235.0                1.374                2.020
8        240.0                1.043                2.451
9        245.0                0.650                1.990
10       250.0                0.372                1.405
11       255.0                0.206                1.097
12       260.0                0.128                1.032
13       265.0                0.100                1.079
14       270.0                0.088                1.156
15       275.0                0.080                1.199
16       280.0                0.072                1.154
17       285.0                0.064                0.994
18       290.0                0.054                0.758
19       295.0                0.045                0.497
20       300.0                0.039                0.360
21       305.0                0.033                0.285
22       310.0                0.029                0.254
23       315.0                0.025                0.237
24       320.0                0.022                0.225
25       325.0                0.019                0.213
26       330.0                0.017                0.197
27       335.0                0.015                0.182
28       340.0                0.013                0.167
29       345.0                0.011                0.155
30       350.0                0.010                0.145
31       355.0                0.009                0.138
32       360.0                0.008                0.132
33       365.0                0.007                0.127
34       370.0                0.006                0.121
35       375.0                0.006                0.116
36       380.0                0.005                0.111
37       385.0                0.005                0.105
38       390.0                0.004                0.099
39       395.0                0.004                0.094
40       400.0                0.003                0.089

In [109]:
# df.to_excel (r'C:\Users\chris\mcb-protein_isolation\data\dataspectra.xlsx', index = False, header=True)

In [123]:
# P1-5 high, od 0.056
y3_data = [0.065, 0.146, 0.146, 0.199, 0.171, 0.415, 1.339, 1.778, 2.179, 2.104, 
          1.133, 0.495, 0.202, 0.098, 0.062, 0.050, 0.044, 0.037, 0.028, 0.018,
          0.013, 0.010, 0.008, 0.008, 0.007, 0.007, 0.006, 0.006, 0.005, 0.004,
          0.004, 0.004, 0.003, 0.002, 0.002, 0.001, 0.000, - 0.001, - 0.002, - 0.003, - 0.004]

In [128]:
y3 = pd.DataFrame(y3_data)
y3 = y3.rename(columns={y3.columns[0]: "Absorbace P1-5 High"})
y3.head()

   Absorbace P1-5 High
0                0.065
1                0.146
2                0.146
3                0.199
4                0.171

In [137]:
# absorbance spectrum analysis data for P2-4 High, od at 280 nm = 3.155
y4_data = [0.639, 0.695, 0.852, 0.652, 0.643, 0.893, 1.587, 2.229, 2.743, 3.117,
          3.235, 3.196, 3.247, 3.162, 3.214, 3.190, 3.200, 3.202, 3.142, 3.044,
          1.995, 1.018, 0.666, 0.569, 0.545, 0.533, 0.522, 0.511, 0.496, 0.481,
          0.464, 0.449, 0.435, 0.421, 0.407, 0.392, 0.378, 0.363, 0.348, 0.332, 0.317]

In [139]:
y4 = pd.DataFrame(y4_data)
y4 = y4.rename(columns={y4.columns[0]: "Absorbace P2-4 High"})
y4.head()

   Absorbace P2-4 High
0                0.639
1                0.695
2                0.852
3                0.652
4                0.643

In [140]:
df = pd.concat([x, y1, y2_df, y3, y4], axis=1)
df

,Wavelength,Absorbance P1-5 Med,Absorbance P2-5 Med,Absorbace P1-5 High,Absorbace P2-4 High
0,200.0,0.142,0.251,0.065,0.639
1,205.0,0.114,0.257,0.146,0.695
2,210.0,0.092,0.432,0.146,0.852
3,215.0,0.067,0.373,0.199,0.652
4,220.0,0.150,0.384,0.171,0.643
5,225.0,0.348,0.720,0.415,0.893
6,230.0,1.216,1.486,1.339,1.587
7,235.0,1.374,2.020,1.778,2.229
8,240.0,1.043,2.451,2.179,2.743
9,245.0,0.650,1.990,2.104,3.117
10,250.0,0.372,1.405,1.133,3.235
11,255.0,0.206,1.097,0.495,3.196
12,260.0,0.128,1.032,0.202,3.247
13,265.0,0.100,1.079,0.098,3.162
14,270.0,0.088,1.156,0.062,3.214
15,275.0,0.080,1.199,0.050,3.190
16,280.0,0.072,1.154,0.044,3.200
17,285.0,0.064,0.994,0.037,3.202
18,290.0,0.054,0.758,0.028,3.142
19,295.0,0.045,0.497,0.018,3.044
20,300.0,0.039,0.360,0.013,1.995
21,305.0,0.033,0.285,0.010,1.018
22,310.0,0.029,0.254,0.008,0.666
23,315.0,0.025,0.237,0.008,0.569
24,320.0,0.022,0.225,0.007,0.545
25,325.0,0.019,0.213,0.007,0.533
26,330.0,0.017,0.197,0.006,0.522
27,335.0,0.015,0.182,0.006,0.511
28,340.0,0.013,0.167,0.005,0.496
29,345.0,0.011,0.155,0.004,0.481
30,350.0,0.010,0.145,0.004,0.464
31,355.0,0.009,0.138,0.004,0.449
32,360.0,0.008,0.132,0.003,0.435
33,365.0,0.007,0.127,0.002,0.421
34,370.0,0.006,0.121,0.002,0.407
35,375.0,0.006,0.116,0.001,0.392
36,380.0,0.005,0.111,0.000,0.378
37,385.0,0.005,0.105,-0.001,0.363
38,390.0,0.004,0.099,-0.002,0.348
39,395.0,0.004,0.094,-0.003,0.332
40,400.0,0.003,0.089,-0.004,0.317

In [142]:
df.to_excel (r'C:\Users\chris\mcb-protein_isolation\data\dataspectra.xlsx', index = False, header=True)